# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
#url: http://www.johndeanossowski.com
baseurl: https://johndeanossowski.github.io/PortfolioSite/
title: John Dean Ossowski
author: John Dean Ossowski
description: Portfolio Site
avatar: profile.png
email: johndeanossowski@gmail.com
github: johndeanossowski # username
twitter: johndeanski
linkedin: johndeanossowski
#stackoverflow: ""   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
